export const categoryMetadata = {
  unorte: { color: "#d10a11", isLocation: true },
  lci: { color: "#F6E05E", isLocation: true },
  tutorias: { color: "#48BB78" },
  worktime: { color: "#63B3ED" },
  doom: { color: "#B91C1C" },
  leer: { color: "#4A90B4" },
  meditacion: { color: "#5A8BAF" },
  jrnl: { color: "#6B95C7" },
  amigos: { color: "#ED8936", isLocation: true },
  "casa bella": { color: "#805AD5", isLocation: true },
  "casa beto": { color: "#3467c6", isLocation: true },
  dormir: { color: "#999", isLocation: true },
  enfermo: { color: "#FC8181" },
  familia: { color: "#ED8936", isLocation: true },
  gym: { color: "#68D391", isLocation: true },
  mdm: { color: "#F687B3", isLocation: true },
  misc: { color: "#A0AEC0", isLocation: true },
  paseo: { color: "#81C784", isLocation: true },
  personal: { color: "#FFB74D" },
  playa: { color: "#4FC3F7", isLocation: true },
  reunion: { color: "#DD0079", isLocation: true },
  snooze: { color: "#90A4AE" },
  tt: { color: "#444", height: "100%", isLocation: true },
  vueltas: { color: "#FF8A65", isLocation: true },
  "yaya casa": { color: "#FF7043", isLocation: true },
  default: {
    color: "#e0e0e0",
    height: "80%",
    radius: "0px",
    isLocation: false,
  },
};
